In [1]:
import pandas as pd
import numpy as np

In [5]:
x = list(range(10))
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
x * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
x + x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
x2 = [n*2 for n in x]
x2

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [10]:
xa = np.array(range(10))
xa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
print(type(x))
print(type(xa))

<class 'list'>
<class 'numpy.ndarray'>


In [12]:
len(xa)

10

In [14]:
x3 = ['a',1,2,5]
x3

['a', 1, 2, 5]

In [15]:
xa1 = np.array(x3)
xa1

array(['a', '1', '2', '5'], dtype='<U21')

In [16]:
xa * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
xa - xa

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [20]:
list(map(lambda n: n*2, x))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [21]:
xa2 = np.array(range(-5,5))
xa2

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [22]:
np.abs(xa2) #abs : 절대값

array([5, 4, 3, 2, 1, 0, 1, 2, 3, 4])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')